//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, Eq)]
#[sea_orm(table_name = "db_attachment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub name: String,
    pub hashcode: String,
    pub item_id: i32,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::db_item::Entity",
        from = "Column::ItemId",
        to = "super::db_item::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbItem,
    #[sea_orm(
        belongs_to = "super::db_user::Entity",
        from = "Column::UserId",
        to = "super::db_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbUser,
}

impl Related<super::db_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbItem.def()
    }
}

impl Related<super::db_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
