//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "db_board_column")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub board_id: i32,
    pub column_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::db_board::Entity",
        from = "Column::BoardId",
        to = "super::db_board::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbBoard,
    #[sea_orm(
        belongs_to = "super::db_column::Entity",
        from = "Column::ColumnId",
        to = "super::db_column::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbColumn,
}

impl Related<super::db_board::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbBoard.def()
    }
}

impl Related<super::db_column::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbColumn.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
