//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "db_board")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub name: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::db_board_column::Entity")]
    DbBoardColumn,
    #[sea_orm(has_many = "super::db_board_user::Entity")]
    DbBoardUser,
}

impl Related<super::db_board_column::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbBoardColumn.def()
    }
}

impl Related<super::db_board_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbBoardUser.def()
    }
}
impl From<Model> for Entity {
    fn from(from: Model) -> Self {
        Self {}
    }
}

impl ActiveModelBehavior for ActiveModel {}
