//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "db_board_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub board_id: i32,
    pub user_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::db_board::Entity",
        from = "Column::BoardId",
        to = "super::db_board::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbBoard,
    #[sea_orm(
        belongs_to = "super::db_user::Entity",
        from = "Column::UserId",
        to = "super::db_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbUser,
}

impl Related<super::db_board::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbBoard.def()
    }
}

impl Related<super::db_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
