//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "db_board")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::db_board_column::Entity")]
    DbBoardColumn,
    #[sea_orm(has_many = "super::db_board_user::Entity")]
    DbBoardUser,
}

impl Related<super::db_board_column::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbBoardColumn.def()
    }
}

impl Related<super::db_board_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbBoardUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
