//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, Eq)]
#[sea_orm(table_name = "db_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub estimated_time: Option<String>,
    pub assignee_id: Option<i32>,
    pub reporter_id: Option<i32>,
    pub publisher_id: Option<i32>,
    pub environment: Option<String>,
    pub issue_type: Option<i32>,
    pub description: Option<String>,
    pub order: i64,
    pub priority: Option<i32>,
    pub column_id: i32,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::db_user::Entity",
        from = "Column::AssigneeId",
        to = "super::db_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbUser3,
    #[sea_orm(
        belongs_to = "super::db_column::Entity",
        from = "Column::ColumnId",
        to = "super::db_column::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbColumn,
    #[sea_orm(
        belongs_to = "super::db_user::Entity",
        from = "Column::PublisherId",
        to = "super::db_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbUser2,
    #[sea_orm(
        belongs_to = "super::db_user::Entity",
        from = "Column::ReporterId",
        to = "super::db_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbUser1,
    #[sea_orm(has_many = "super::db_message::Entity")]
    DbMessage,
    #[sea_orm(has_many = "super::db_attachment::Entity")]
    DbAttachment,
}

impl Related<super::db_column::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbColumn.def()
    }
}

impl Related<super::db_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbMessage.def()
    }
}

impl Related<super::db_attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbAttachment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
