//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "db_role_permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub permission_id: i32,
    pub role_id: i32,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::db_permission::Entity",
        from = "Column::PermissionId",
        to = "super::db_permission::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbPermission,
    #[sea_orm(
        belongs_to = "super::db_role::Entity",
        from = "Column::RoleId",
        to = "super::db_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DbRole,
}

impl Related<super::db_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbPermission.def()
    }
}

impl Related<super::db_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DbRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
